name: Auto Reel Generator (Docker)

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t reel-bot .

      - name: Run Container
        env:
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
        run: |
          docker run \
            -e PEXELS_API_KEY=$PEXELS_API_KEY \
            -v ${{ github.workspace }}:/app \
            reel-bot

      - name: Commit reel
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@example.com"
          git add .
          git commit -m "new reel" || echo "no changes"
          git push
